name: update-crops
on:
  schedule:
    - cron: '0 0 * * *'   # 每日 00:00 UTC
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Fetch crops
        run: python scripts/fetch_crops.py
      - name: Commit & push if changed
        run: |
          git config user.name  "crop-bot"
          git config user.email "actions@github.com"
          git diff --quiet || (git add data && git commit -m "chore: sync crops" && git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          ) 